title: Xuefeng Hu | Ph.D. student at USC
description: >
  Xuefeng Hu, Ph.D student at Computer Science Department @ University of South California.

copyright: untitled
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: stratajekylldemo
facebook_username: "xuefeng.leon.hu"
twitter_username: 
linkedin_username: "xuefeng-hu-137b9485"
instagram_username: "xuefenghu"
pinterest_username: "huxuefeng1994"
flickr_username:
github_username:  "michiganleon"
feed_icon:
email: "xuefengh at usc.edu"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
